import Head from 'next/head'
import Header from '../components/header'
import HomePageMainContent from '../components/homePageMainContent'
import Sidebar from '../components/sidebar'
import styles from '../styles/Home.module.css'
import {useAuthState} from 'react-firebase-hooks/auth' 
import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import {auth} from '../firebaseConfig'
import { Auth, getAuth, onAuthStateChanged, User } from 'firebase/auth'
import { AuthUserContext } from '../context/userContext'

export default () => {
  const router = useRouter()

  useEffect(() => {
    auth.onAuthStateChanged((user) => {
      if (user == null)
        router.push('/login')
    })
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/*<Sidebar />*/}
        <HomePageMainContent />
      </main>
    </div>
  )
}
